[package]
name = "quoridor"
version = "0.1.0"
authors = ["Christian *George* Sanger <paperclipstudio@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.8.0"
# priority-queue = "1.1.1"